baseurl: /cgbk

# gems:
#   - jekyll-pandoc

# markdown: pandoc
# pandoc:
#   extensions:
#     - smart
#     - mathjax

markdown: redcarpet
redcarpet:
  extensions:
    - fenced_code_blocks
    - smart
    - footnotes

highlighter: pygments

