baseurl: /cgbk

gems:
  - jekyll-pandoc
  - jekyll-smartify

# markdown: pandoc
# pandoc:
#   extensions:
#     - smart
#     - mathjax

markdown: redcarpet
redcarpet:
 extensions:
   - fenced_code_blocks
   - smart

highlighter: pygments
