baseurl: /cgbk

# gems:
#   - jekyll-pandoc

highlighter: pygments

# markdown: pandoc
# pandoc:
#   extensions:
#     - smart
#     - mathjax

markdown: redcarpet
redcarpet:
  extensions:
    - fenced_code_blocks
    - smart
    - footnotes
    - xhtml
    - no_intra_emphasis
